### ISSUE TITLE
Cannot create  security group icmp rule.

### ISSUE THREAD

**Issue by xuyuji9000** [CuriosityChina/terraform-qingcloud#14]
Related project code:

https://github.com/CuriosityChina/terraform-qingcloud/blob/e51009207922c6fb554f7b1bd9aafff2c8a8ba06/qingcloud/resource_qingcloud_security_group_rule.go#L44-L53

Error:

![image](https://user-images.githubusercontent.com/4877346/39597358-b2d0bb90-4f47-11e8-8f30-8db58db2d170.png)

Related terraform configuration:

```terraform
resource "qingcloud_security_group_rule" "allow-in-ping"{
  name = "允许使用ping"
  security_group_id = "${qingcloud_security_group.basic.id}"
  protocol = "icmp"
  priority = 1
  action = "accept"
  direction = 0
  from_port = "Echo"
  to_port = "echo request"
}
```

**Comment by magicshui** [comment]
thanks for your comments, since we  had  contributed this provider to qingcloud serval months ago, we will not maintain this repo anymore, please use qingcloud's  official provider https://github.com/yunify/terraform-provider-qingcloud 
i think using the new official provider you can solve this issue
